# E-ink palette for zsh-syntax-highlighting (dark mode) -- AUTO-GENERATED by theme/generate.sh
ZSH_HIGHLIGHT_HIGHLIGHTERS=(main cursor)
typeset -gA ZSH_HIGHLIGHT_STYLES

## Comments
ZSH_HIGHLIGHT_STYLES[comment]='fg=#727272'
## Functions/commands
ZSH_HIGHLIGHT_STYLES[alias]='fg=#CCCCCC'
ZSH_HIGHLIGHT_STYLES[suffix-alias]='fg=#CCCCCC'
ZSH_HIGHLIGHT_STYLES[global-alias]='fg=#CCCCCC'
ZSH_HIGHLIGHT_STYLES[function]='fg=#CCCCCC'
ZSH_HIGHLIGHT_STYLES[command]='fg=#CCCCCC'
ZSH_HIGHLIGHT_STYLES[precommand]='fg=#CCCCCC,italic'
ZSH_HIGHLIGHT_STYLES[autodirectory]='fg=#B8B8B8,italic'
ZSH_HIGHLIGHT_STYLES[single-hyphen-option]='fg=#B8B8B8'
ZSH_HIGHLIGHT_STYLES[double-hyphen-option]='fg=#B8B8B8'
ZSH_HIGHLIGHT_STYLES[back-quoted-argument]='fg=#D699B6'
## Built-ins
ZSH_HIGHLIGHT_STYLES[builtin]='fg=#CCCCCC'
ZSH_HIGHLIGHT_STYLES[reserved-word]='fg=#CCCCCC'
ZSH_HIGHLIGHT_STYLES[hashed-command]='fg=#CCCCCC'
## Punctuation
ZSH_HIGHLIGHT_STYLES[commandseparator]='fg=#E67E80'
ZSH_HIGHLIGHT_STYLES[command-substitution-delimiter]='fg=#A4A4A4'
ZSH_HIGHLIGHT_STYLES[command-substitution-delimiter-unquoted]='fg=#A4A4A4'
ZSH_HIGHLIGHT_STYLES[process-substitution-delimiter]='fg=#A4A4A4'
ZSH_HIGHLIGHT_STYLES[back-quoted-argument-delimiter]='fg=#E67E80'
ZSH_HIGHLIGHT_STYLES[back-double-quoted-argument]='fg=#E67E80'
ZSH_HIGHLIGHT_STYLES[back-dollar-quoted-argument]='fg=#E67E80'
## Strings
ZSH_HIGHLIGHT_STYLES[command-substitution-quoted]='fg=#DBBC7F'
ZSH_HIGHLIGHT_STYLES[command-substitution-delimiter-quoted]='fg=#DBBC7F'
ZSH_HIGHLIGHT_STYLES[single-quoted-argument]='fg=#DBBC7F'
ZSH_HIGHLIGHT_STYLES[single-quoted-argument-unclosed]='fg=#E67E80'
ZSH_HIGHLIGHT_STYLES[double-quoted-argument]='fg=#DBBC7F'
ZSH_HIGHLIGHT_STYLES[double-quoted-argument-unclosed]='fg=#E67E80'
ZSH_HIGHLIGHT_STYLES[rc-quote]='fg=#DBBC7F'
## Variables
ZSH_HIGHLIGHT_STYLES[dollar-quoted-argument]='fg=#A4A4A4'
ZSH_HIGHLIGHT_STYLES[dollar-quoted-argument-unclosed]='fg=#E67E80'
ZSH_HIGHLIGHT_STYLES[dollar-double-quoted-argument]='fg=#A4A4A4'
ZSH_HIGHLIGHT_STYLES[assign]='fg=#A4A4A4'
ZSH_HIGHLIGHT_STYLES[named-fd]='fg=#A4A4A4'
ZSH_HIGHLIGHT_STYLES[numeric-fd]='fg=#A4A4A4'
## Misc
ZSH_HIGHLIGHT_STYLES[unknown-token]='fg=#E67E80'
ZSH_HIGHLIGHT_STYLES[path]='fg=#A4A4A4,underline'
ZSH_HIGHLIGHT_STYLES[path_pathseparator]='fg=#E67E80,underline'
ZSH_HIGHLIGHT_STYLES[path_prefix]='fg=#A4A4A4,underline'
ZSH_HIGHLIGHT_STYLES[path_prefix_pathseparator]='fg=#E67E80,underline'
ZSH_HIGHLIGHT_STYLES[globbing]='fg=#A4A4A4'
ZSH_HIGHLIGHT_STYLES[history-expansion]='fg=#D699B6'
ZSH_HIGHLIGHT_STYLES[back-quoted-argument-unclosed]='fg=#E67E80'
ZSH_HIGHLIGHT_STYLES[redirection]='fg=#A4A4A4'
ZSH_HIGHLIGHT_STYLES[arg0]='fg=#A4A4A4'
ZSH_HIGHLIGHT_STYLES[default]='fg=#A4A4A4'
ZSH_HIGHLIGHT_STYLES[cursor]='fg=#A4A4A4'
