#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
DOTFILES_DIR="$SCRIPT_DIR/.."
MODE="${1:-dark}"
MODE_UPPER="${MODE^^}"

if [[ "$MODE" != "dark" && "$MODE" != "light" ]]; then
    echo "Usage: generate.sh [dark|light]"
    exit 1
fi

source "$SCRIPT_DIR/palette.sh"

# Resolve a color name for current mode via indirect variable expansion
color() {
    local var="${MODE_UPPER}_${1}"
    echo "${!var}"
}

MONO_NAMES=(MONO1 MONO2 MONO3 MONO4 MONO5 MONO6 MONO7 MONO8
            MONO9 MONO10 MONO11 MONO12 MONO13 MONO14 MONO15 MONO16)
ACCENT_NAMES=(RED YELLOW GREEN BLUE AQUA PURPLE ORANGE CACTUS GRASS FRUIT BRICK BROWN CYAN)

SEMANTIC_NAMES=(BG SURFACE OVERLAY FAINT DIM MUTED SUBTLE BORDER SECONDARY TERTIARY FG EMPHASIS STRONG BRIGHT INTENSE ERROR WARNING OK INFO HINT SEARCH VCS_ADD VCS_CHANGE VCS_REMOVE DIFF_ADD DIFF_CHANGE DIFF_REMOVE)

emit_hypr_color() {
    local name="$1"
    local value="$(color "$name")"
    echo "\$${name,,} = rgb(${value})"
    echo "\$${name,,}Alpha = ${value}"
}

emit_css_color() {
    local name="$1"
    echo "@define-color ${name,,} #$(color "$name");"
}

generate_hyprland() {
    local out="$DOTFILES_DIR/hyprland/.config/hypr/e-ink.conf"
    {
        echo "# E-ink palette for Hyprland ($MODE mode) -- AUTO-GENERATED by theme/generate.sh"
        echo "# Mono greyscale"
        for name in "${MONO_NAMES[@]}"; do
            emit_hypr_color "$name"
        done
        echo ""
        echo "# Cactusbuddy accents"
        for name in "${ACCENT_NAMES[@]}"; do
            emit_hypr_color "$name"
        done
        echo ""
        echo "# Semantic aliases"
        for name in "${SEMANTIC_NAMES[@]}"; do
            emit_hypr_color "$name"
        done
    } > "$out"
}

generate_waybar() {
    local out="$DOTFILES_DIR/waybar/.config/waybar/e-ink.css"
    {
        echo "/* E-ink palette for Waybar ($MODE mode) -- AUTO-GENERATED by theme/generate.sh */"
        echo "/* Mono greyscale */"
        for name in "${MONO_NAMES[@]}"; do
            emit_css_color "$name"
        done
        echo ""
        echo "/* Cactusbuddy accents */"
        for name in "${ACCENT_NAMES[@]}"; do
            emit_css_color "$name"
        done
        echo ""
        echo "/* Semantic aliases */"
        for name in "${SEMANTIC_NAMES[@]}"; do
            emit_css_color "$name"
        done
    } > "$out"
}

generate_starship_palettes() {
    echo "# BEGIN E-INK GENERATED PALETTES"
    echo "# AUTO-GENERATED by theme/generate.sh from theme/palette.sh"

    for variant in dark light; do
        local V="${variant^^}"
        local previous="$MODE_UPPER"
        MODE_UPPER="$V"

        echo ""
        echo "[palettes.e_ink_${variant}]"
        echo "# Mono greyscale"
        for name in "${MONO_NAMES[@]}"; do
            echo "${name,,} = \"#$(color "$name")\""
        done
        echo "# Cactusbuddy accents"
        for name in "${ACCENT_NAMES[@]}"; do
            echo "${name,,} = \"#$(color "$name")\""
        done
        echo "# Semantic aliases"
        for name in "${SEMANTIC_NAMES[@]}"; do
            echo "${name,,} = \"#$(color "$name")\""
        done

        MODE_UPPER="$previous"
    done

    echo "# END E-INK GENERATED PALETTES"
}

generate_starship() {
    local conf="$DOTFILES_DIR/starship/.config/starship.toml"
    local tmp palettes
    tmp="$(mktemp)"
    palettes="$(mktemp)"

    generate_starship_palettes > "$palettes"

    awk -v mode="$MODE" -v palettes="$palettes" '
        function print_palettes(   line) {
            while ((getline line < palettes) > 0) print line
            close(palettes)
        }

        /^palette = / {
            print "palette = '\''e_ink_" mode "'\''"
            next
        }

        /^# BEGIN E-INK GENERATED PALETTES$/ {
            print_palettes()
            skipping = 1
            inserted = 1
            next
        }

        skipping && /^# END E-INK GENERATED PALETTES$/ {
            skipping = 0
            next
        }

        skipping {
            next
        }

        !inserted && /^\[palettes\.e_ink_dark\]$/ {
            print_palettes()
            skipping_legacy = 1
            inserted = 1
            next
        }

        skipping_legacy && /^\[[^]]+\]$/ && $0 !~ /^\[palettes\.e_ink_/ {
            skipping_legacy = 0
            print
            next
        }

        skipping_legacy {
            next
        }

        { print }
    ' "$conf" > "$tmp"

    mv "$tmp" "$conf"
    rm -f "$palettes"
}

generate_tmux() {
    local out="$DOTFILES_DIR/tmux/e-ink.tmux.conf"
    local bg="$(color BG)"
    local fg="$(color FG)"
    local fg_dim="$(color MUTED)"
    local fg_bright="$(color BRIGHT)"
    local border="$(color OVERLAY)"
    local border_active="$(color OK)"
    local accent="$(color OK)"
    {
        echo "# E-ink palette for tmux ($MODE mode) -- AUTO-GENERATED by theme/generate.sh"
        echo ""
        echo "# Pane borders"
        echo "set -g pane-border-style fg=#${border}"
        echo "set -g pane-active-border-style fg=#${border_active}"
        echo ""
        echo "# Status bar"
        echo "set -g status-style bg=default,fg=#${fg}"
        echo "set -g status-left \"\""
        echo "set -g status-right \"#[fg=#${fg_dim}]#S\""
        echo ""
        echo "# Window list"
        echo "set -g window-status-format \"#[fg=#${fg_dim}] #I #W \""
        echo "set -g window-status-current-format \"#[fg=#${accent},bold] #I #W \""
        echo "set -g window-status-separator \"\""
        echo ""
        echo "# Messages & command line"
        echo "set -g message-style bg=#${bg},fg=#${fg_bright}"
        echo "set -g message-command-style bg=#${bg},fg=#${fg_bright}"
        echo ""
        echo "# Mode (copy mode, etc.)"
        echo "set -g mode-style bg=#${border},fg=#${fg_bright}"
    } > "$out"
}

generate_firefox() {
    local out="$DOTFILES_DIR/firefox/extensions/e-ink-theme/themes.js"
    {
        echo "// E-ink Firefox theme palettes -- AUTO-GENERATED by theme/generate.sh"
        echo "const THEMES = {"

        for variant in dark light; do
            local V="${variant^^}"
            local v="$variant"
            # helper to resolve color for this variant
            _c() { local var="${V}_${1}"; echo "#${!var}"; }

            echo "  \"$v\": {"
            echo "    colors: {"
            echo "      frame: \"$(_c BG)\","
            echo "      frame_inactive: \"$(_c BG)\","
            echo "      tab_background_text: \"$(_c FG)\","
            echo "      tab_text: \"$(_c INTENSE)\","
            echo "      tab_selected: \"$(_c SURFACE)\","
            echo "      tab_line: \"$(_c SEARCH)\","
            echo "      tab_loading: \"$(_c INFO)\","
            echo "      toolbar: \"$(_c SURFACE)\","
            echo "      toolbar_text: \"$(_c STRONG)\","
            echo "      bookmark_text: \"$(_c STRONG)\","
            echo "      icons: \"$(_c HINT)\","
            echo "      icons_attention: \"$(_c ERROR)\","
            echo "      toolbar_field: \"$(_c BG)\","
            echo "      toolbar_field_text: \"$(_c BRIGHT)\","
            echo "      toolbar_field_border: \"$(_c HINT)\","
            echo "      toolbar_field_focus: \"$(_c SURFACE)\","
            echo "      toolbar_field_highlight: \"$(_c SEARCH)\","
            echo "      toolbar_field_highlight_text: \"$(_c BG)\","
            echo "      toolbar_top_separator: \"transparent\","
            echo "      toolbar_bottom_separator: \"$(_c HINT)\","
            echo "      button_background_hover: \"$(_c OVERLAY)\","
            echo "      button_background_active: \"$(_c SEARCH)\","
            echo "      popup: \"$(_c SURFACE)\","
            echo "      popup_text: \"$(_c STRONG)\","
            echo "      popup_highlight: \"$(_c HINT)\","
            echo "      popup_highlight_text: \"$(_c BG)\","
            echo "      popup_border: \"$(_c HINT)\","
            echo "      sidebar: \"$(_c BG)\","
            echo "      sidebar_text: \"$(_c FG)\","
            echo "      sidebar_border: \"$(_c HINT)\","
            echo "      sidebar_highlight: \"$(_c OVERLAY)\","
            echo "      sidebar_highlight_text: \"$(_c INTENSE)\","
            echo "      ntp_background: \"$(_c BG)\","
            echo "      ntp_text: \"$(_c FG)\","
            echo "      ntp_card_background: \"$(_c SURFACE)\","
            echo "    }"
            echo "  },"
        done

        echo "};"
    } > "$out"
}

generate_kitty() {
    local out="$DOTFILES_DIR/kitty/.config/kitty/e-ink-theme.conf"
    {
        echo "# E-ink palette for kitty ($MODE mode) -- AUTO-GENERATED by theme/generate.sh"
        echo ""
        echo "foreground              #$(color FG)"
        echo "background              #$(color BG)"
        echo "selection_foreground    #$(color BG)"
        echo "selection_background    #$(color STRONG)"
        echo ""
        echo "cursor                  #$(color INTENSE)"
        echo "cursor_text_color       #$(color BG)"
        echo ""
        echo "url_color               #$(color HINT)"
        echo ""
        echo "active_border_color     #$(color OK)"
        echo "inactive_border_color   #$(color BORDER)"
        echo "bell_border_color       #$(color WARNING)"
        echo ""
        echo "wayland_titlebar_color system"
        echo "macos_titlebar_color system"
        echo ""
        echo "active_tab_foreground   #$(color BG)"
        echo "active_tab_background   #$(color INTENSE)"
        echo "inactive_tab_foreground #$(color MUTED)"
        echo "inactive_tab_background #$(color SURFACE)"
        echo "tab_bar_background      #$(color BG)"
        echo ""
        echo "mark1_foreground #$(color BG)"
        echo "mark1_background #$(color HINT)"
        echo "mark2_foreground #$(color BG)"
        echo "mark2_background #$(color SEARCH)"
        echo "mark3_foreground #$(color BG)"
        echo "mark3_background #$(color INFO)"
        echo ""
        echo "# The 16 terminal colors"
        echo "# black"
        echo "color0 #$(color BG)"
        echo "color8 #$(color BORDER)"
        echo ""
        echo "# red"
        echo "color1 #$(color ERROR)"
        echo "color9 #$(color ERROR)"
        echo ""
        echo "# green"
        echo "color2  #$(color OK)"
        echo "color10 #$(color OK)"
        echo ""
        echo "# yellow"
        echo "color3  #$(color WARNING)"
        echo "color11 #$(color WARNING)"
        echo ""
        echo "# blue"
        echo "color4  #$(color HINT)"
        echo "color12 #$(color HINT)"
        echo ""
        echo "# magenta"
        echo "color5  #$(color PURPLE)"
        echo "color13 #$(color PURPLE)"
        echo ""
        echo "# cyan"
        echo "color6  #$(color INFO)"
        echo "color14 #$(color INFO)"
        echo ""
        echo "# white"
        echo "color7  #$(color BRIGHT)"
        echo "color15 #$(color INTENSE)"
    } > "$out"
}

generate_zsh() {
    local out="$DOTFILES_DIR/zshrc/.zsh-syntax-highlighting-theme.zsh"
    local fg="#$(color FG)"
    local intense="#$(color INTENSE)"
    local strong="#$(color STRONG)"
    local muted="#$(color MUTED)"
    local error="#$(color ERROR)"
    local ok="#$(color OK)"
    local warning="#$(color WARNING)"
    local search="#$(color SEARCH)"
    local hint="#$(color HINT)"
    local purple="#$(color PURPLE)"
    {
        echo "# E-ink palette for zsh-syntax-highlighting ($MODE mode) -- AUTO-GENERATED by theme/generate.sh"
        echo "ZSH_HIGHLIGHT_HIGHLIGHTERS=(main cursor)"
        echo "typeset -gA ZSH_HIGHLIGHT_STYLES"
        echo ""
        echo "## Comments"
        echo "ZSH_HIGHLIGHT_STYLES[comment]='fg=${muted}'"
        echo "## Functions/commands"
        echo "ZSH_HIGHLIGHT_STYLES[alias]='fg=${intense}'"
        echo "ZSH_HIGHLIGHT_STYLES[suffix-alias]='fg=${intense}'"
        echo "ZSH_HIGHLIGHT_STYLES[global-alias]='fg=${intense}'"
        echo "ZSH_HIGHLIGHT_STYLES[function]='fg=${intense}'"
        echo "ZSH_HIGHLIGHT_STYLES[command]='fg=${intense}'"
        echo "ZSH_HIGHLIGHT_STYLES[precommand]='fg=${intense}'"
        echo "ZSH_HIGHLIGHT_STYLES[autodirectory]='fg=${strong}'"
        echo "ZSH_HIGHLIGHT_STYLES[single-hyphen-option]='fg=${strong}'"
        echo "ZSH_HIGHLIGHT_STYLES[double-hyphen-option]='fg=${strong}'"
        echo "ZSH_HIGHLIGHT_STYLES[back-quoted-argument]='fg=${purple}'"
        echo "## Built-ins"
        echo "ZSH_HIGHLIGHT_STYLES[builtin]='fg=${intense}'"
        echo "ZSH_HIGHLIGHT_STYLES[reserved-word]='fg=${intense}'"
        echo "ZSH_HIGHLIGHT_STYLES[hashed-command]='fg=${intense}'"
        echo "## Punctuation"
        echo "ZSH_HIGHLIGHT_STYLES[commandseparator]='fg=${error}'"
        echo "ZSH_HIGHLIGHT_STYLES[command-substitution-delimiter]='fg=${fg}'"
        echo "ZSH_HIGHLIGHT_STYLES[command-substitution-delimiter-unquoted]='fg=${fg}'"
        echo "ZSH_HIGHLIGHT_STYLES[process-substitution-delimiter]='fg=${fg}'"
        echo "ZSH_HIGHLIGHT_STYLES[back-quoted-argument-delimiter]='fg=${error}'"
        echo "ZSH_HIGHLIGHT_STYLES[back-double-quoted-argument]='fg=${error}'"
        echo "ZSH_HIGHLIGHT_STYLES[back-dollar-quoted-argument]='fg=${error}'"
        echo "## Strings"
        echo "ZSH_HIGHLIGHT_STYLES[command-substitution-quoted]='fg=${warning}'"
        echo "ZSH_HIGHLIGHT_STYLES[command-substitution-delimiter-quoted]='fg=${warning}'"
        echo "ZSH_HIGHLIGHT_STYLES[single-quoted-argument]='fg=${warning}'"
        echo "ZSH_HIGHLIGHT_STYLES[single-quoted-argument-unclosed]='fg=${error}'"
        echo "ZSH_HIGHLIGHT_STYLES[double-quoted-argument]='fg=${warning}'"
        echo "ZSH_HIGHLIGHT_STYLES[double-quoted-argument-unclosed]='fg=${error}'"
        echo "ZSH_HIGHLIGHT_STYLES[rc-quote]='fg=${warning}'"
        echo "## Variables"
        echo "ZSH_HIGHLIGHT_STYLES[dollar-quoted-argument]='fg=${fg}'"
        echo "ZSH_HIGHLIGHT_STYLES[dollar-quoted-argument-unclosed]='fg=${error}'"
        echo "ZSH_HIGHLIGHT_STYLES[dollar-double-quoted-argument]='fg=${fg}'"
        echo "ZSH_HIGHLIGHT_STYLES[assign]='fg=${fg}'"
        echo "ZSH_HIGHLIGHT_STYLES[named-fd]='fg=${fg}'"
        echo "ZSH_HIGHLIGHT_STYLES[numeric-fd]='fg=${fg}'"
        echo "## Misc"
        echo "ZSH_HIGHLIGHT_STYLES[unknown-token]='fg=${error}'"
        echo "ZSH_HIGHLIGHT_STYLES[path]='fg=${fg},underline'"
        echo "ZSH_HIGHLIGHT_STYLES[path_pathseparator]='fg=${error},underline'"
        echo "ZSH_HIGHLIGHT_STYLES[path_prefix]='fg=${fg},underline'"
        echo "ZSH_HIGHLIGHT_STYLES[path_prefix_pathseparator]='fg=${error},underline'"
        echo "ZSH_HIGHLIGHT_STYLES[globbing]='fg=${fg}'"
        echo "ZSH_HIGHLIGHT_STYLES[history-expansion]='fg=${purple}'"
        echo "ZSH_HIGHLIGHT_STYLES[back-quoted-argument-unclosed]='fg=${error}'"
        echo "ZSH_HIGHLIGHT_STYLES[redirection]='fg=${fg}'"
        echo "ZSH_HIGHLIGHT_STYLES[arg0]='fg=${fg}'"
        echo "ZSH_HIGHLIGHT_STYLES[default]='fg=${fg}'"
        echo "ZSH_HIGHLIGHT_STYLES[cursor]='fg=${fg}'"
    } > "$out"
}

generate_waybar_config() {
    local tpl="$DOTFILES_DIR/waybar/.config/waybar/config.jsonc.tpl"
    local out="$DOTFILES_DIR/waybar/.config/waybar/config.jsonc"
    local content
    # Skip the first line (template banner comment) when reading
    content="$(tail -n +2 "$tpl")"
    # Substitute each placeholder with the resolved semantic hex for the current mode
    for name in STRONG FG WARNING ERROR OK; do
        content="${content//@@${name}@@/#$(color "$name")}"
    done
    {
        echo "// E-ink waybar config ($MODE mode) -- AUTO-GENERATED by theme/generate.sh"
        printf '%s\n' "$content"
    } > "$out"
}

generate_wofi() {
    local out="$DOTFILES_DIR/wofi/.config/wofi/e-ink.css"
    {
        echo "/* E-ink palette for Wofi ($MODE mode) -- AUTO-GENERATED by theme/generate.sh */"
        echo "/* Mono greyscale */"
        for name in "${MONO_NAMES[@]}"; do
            emit_css_color "$name"
        done
        echo ""
        echo "/* Cactusbuddy accents */"
        for name in "${ACCENT_NAMES[@]}"; do
            emit_css_color "$name"
        done
        echo ""
        echo "/* Semantic aliases */"
        for name in "${SEMANTIC_NAMES[@]}"; do
            emit_css_color "$name"
        done
    } > "$out"
}

generate_ghostty() {
    local out="$DOTFILES_DIR/ghostty/.config/ghostty/e-ink-theme.conf"
    {
        echo "# E-ink palette for Ghostty ($MODE mode) -- AUTO-GENERATED by theme/generate.sh"
        echo ""
        echo "background = #$(color BG)"
        echo "foreground = #$(color FG)"
        echo "selection-foreground = #$(color BG)"
        echo "selection-background = #$(color STRONG)"
        echo "cursor-color = #$(color INTENSE)"
        echo "cursor-text = #$(color BG)"
        echo ""
        echo "palette = 0=#$(color BG)"
        echo "palette = 1=#$(color ERROR)"
        echo "palette = 2=#$(color OK)"
        echo "palette = 3=#$(color WARNING)"
        echo "palette = 4=#$(color HINT)"
        echo "palette = 5=#$(color PURPLE)"
        echo "palette = 6=#$(color INFO)"
        echo "palette = 7=#$(color BRIGHT)"
        echo "palette = 8=#$(color BORDER)"
        echo "palette = 9=#$(color ERROR)"
        echo "palette = 10=#$(color OK)"
        echo "palette = 11=#$(color WARNING)"
        echo "palette = 12=#$(color HINT)"
        echo "palette = 13=#$(color PURPLE)"
        echo "palette = 14=#$(color INFO)"
        echo "palette = 15=#$(color INTENSE)"
    } > "$out"
}

generate_hyprland
generate_waybar
generate_starship
generate_tmux
generate_firefox
generate_kitty
generate_zsh
generate_waybar_config
generate_wofi
generate_ghostty

echo "Generated e-ink $MODE theme for hyprland, waybar, waybar-config, starship, tmux, firefox, kitty, zsh, wofi, ghostty."
