#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
DOTFILES_DIR="$SCRIPT_DIR/.."
MODE="${1:-dark}"
MODE_UPPER="${MODE^^}"

source "$SCRIPT_DIR/palette.sh"

# Resolve a color name for current mode via indirect variable expansion
color() {
    local var="${MODE_UPPER}_${1}"
    echo "${!var}"
}

MONO_NAMES=(MONO1 MONO2 MONO3 MONO4 MONO5 MONO6 MONO7 MONO8
            MONO9 MONO10 MONO11 MONO12 MONO13 MONO14 MONO15 MONO16)
ACCENT_NAMES=(RED YELLOW GREEN BLUE AQUA PURPLE ORANGE)

generate_hyprland() {
    local out="$DOTFILES_DIR/hyprland/.config/hypr/e-ink.conf"
    {
        echo "# E-ink palette for Hyprland ($MODE mode) -- AUTO-GENERATED by theme/generate.sh"
        echo "# Mono greyscale"
        for name in "${MONO_NAMES[@]}"; do
            echo "\$${name,,} = rgb($(color "$name"))"
        done
        echo ""
        echo "# Everforest accents"
        for name in "${ACCENT_NAMES[@]}"; do
            echo "\$${name,,} = rgb($(color "$name"))"
        done
    } > "$out"
}

generate_waybar() {
    local out="$DOTFILES_DIR/waybar/.config/waybar/e-ink.css"
    {
        echo "/* E-ink palette for Waybar ($MODE mode) -- AUTO-GENERATED by theme/generate.sh */"
        echo "/* Mono greyscale */"
        for name in "${MONO_NAMES[@]}"; do
            echo "@define-color ${name,,} #$(color "$name");"
        done
        echo ""
        echo "/* Everforest accents */"
        for name in "${ACCENT_NAMES[@]}"; do
            echo "@define-color ${name,,} #$(color "$name");"
        done
    } > "$out"
}

generate_starship() {
    local conf="$DOTFILES_DIR/starship/.config/starship.toml"
    sed -i "s/^palette = .*/palette = 'e_ink_${MODE}'/" "$conf"
}

generate_tmux() {
    local out="$DOTFILES_DIR/tmux/e-ink.tmux.conf"
    local bg="$(color MONO1)"
    local fg="$(color MONO12)"
    local fg_dim="$(color MONO7)"
    local fg_bright="$(color MONO15)"
    local border="$(color MONO4)"
    local border_active="$(color GREEN)"
    local accent="$(color GREEN)"
    {
        echo "# E-ink palette for tmux ($MODE mode) -- AUTO-GENERATED by theme/generate.sh"
        echo ""
        echo "# Pane borders"
        echo "set -g pane-border-style fg=#${border}"
        echo "set -g pane-active-border-style fg=#${border_active}"
        echo ""
        echo "# Status bar"
        echo "set -g status-style bg=default,fg=#${fg}"
        echo "set -g status-left \"\""
        echo "set -g status-right \"#[fg=#${fg_dim}]#S\""
        echo ""
        echo "# Window list"
        echo "set -g window-status-format \"#[fg=#${fg_dim}] #I #W \""
        echo "set -g window-status-current-format \"#[fg=#${accent},bold] #I #W \""
        echo "set -g window-status-separator \"\""
        echo ""
        echo "# Messages & command line"
        echo "set -g message-style bg=#${bg},fg=#${fg_bright}"
        echo "set -g message-command-style bg=#${bg},fg=#${fg_bright}"
        echo ""
        echo "# Mode (copy mode, etc.)"
        echo "set -g mode-style bg=#${border},fg=#${fg_bright}"
    } > "$out"
}

generate_hyprland
generate_waybar
generate_starship
generate_tmux

echo "Generated e-ink $MODE theme for hyprland, waybar, starship, tmux."
