#!/usr/bin/env bash
# E-ink color palette — single source of truth
# Derived from e-ink.nvim/lua/e-ink/palette.lua
# Format: VARIANT_NAME=HEXVALUE (no # prefix)

# --- Dark mono (16 greyscale shades, dark to light) ---
DARK_MONO1=333333
DARK_MONO2=474747
DARK_MONO3=4A4A4A
DARK_MONO4=545454
DARK_MONO5=5E5E5E
DARK_MONO6=686868
DARK_MONO7=727272
DARK_MONO8=7C7C7C
DARK_MONO9=868686
DARK_MONO10=909090
DARK_MONO11=9A9A9A
DARK_MONO12=A4A4A4
DARK_MONO13=AEAEAE
DARK_MONO14=B8B8B8
DARK_MONO15=C2C2C2
DARK_MONO16=CCCCCC

# --- Light mono (reversed) ---
LIGHT_MONO1=CCCCCC
LIGHT_MONO2=C2C2C2
LIGHT_MONO3=B8B8B8
LIGHT_MONO4=AEAEAE
LIGHT_MONO5=A4A4A4
LIGHT_MONO6=9A9A9A
LIGHT_MONO7=909090
LIGHT_MONO8=868686
LIGHT_MONO9=7C7C7C
LIGHT_MONO10=727272
LIGHT_MONO11=686868
LIGHT_MONO12=5E5E5E
LIGHT_MONO13=545454
LIGHT_MONO14=4A4A4A
LIGHT_MONO15=474747
LIGHT_MONO16=333333

# --- Dark everforest accents ---
DARK_RED=E67E80
DARK_YELLOW=DBBC7F
DARK_GREEN=A7C080
DARK_BLUE=7FBBB3
DARK_AQUA=83C092
DARK_PURPLE=D699B6
DARK_ORANGE=E69875

# --- Light everforest accents ---
LIGHT_RED=F85552
LIGHT_YELLOW=DFA000
LIGHT_GREEN=8DA101
LIGHT_BLUE=3A94C5
LIGHT_AQUA=35A77C
LIGHT_PURPLE=DF69BA
LIGHT_ORANGE=F57D26

# --- Background accent colors ---
DARK_BG_RED=4C3743
DARK_BG_GREEN=3C4841
DARK_BG_BLUE=384B55
LIGHT_BG_RED=FFE7DE
LIGHT_BG_GREEN=f3f5d9
LIGHT_BG_BLUE=ECF5ED

# --- Semantic mono aliases (dark) ---
DARK_BG=$DARK_MONO1
DARK_SURFACE=$DARK_MONO2
DARK_OVERLAY=$DARK_MONO4
DARK_FAINT=$DARK_MONO5
DARK_DIM=$DARK_MONO6
DARK_MUTED=$DARK_MONO7
DARK_SUBTLE=$DARK_MONO8
DARK_BORDER=$DARK_MONO9
DARK_SECONDARY=$DARK_MONO10
DARK_TERTIARY=$DARK_MONO11
DARK_FG=$DARK_MONO12
DARK_EMPHASIS=$DARK_MONO13
DARK_STRONG=$DARK_MONO14
DARK_BRIGHT=$DARK_MONO15
DARK_INTENSE=$DARK_MONO16

# --- Semantic mono aliases (light) ---
LIGHT_BG=$LIGHT_MONO1
LIGHT_SURFACE=$LIGHT_MONO2
LIGHT_OVERLAY=$LIGHT_MONO4
LIGHT_FAINT=$LIGHT_MONO5
LIGHT_DIM=$LIGHT_MONO6
LIGHT_MUTED=$LIGHT_MONO7
LIGHT_SUBTLE=$LIGHT_MONO8
LIGHT_BORDER=$LIGHT_MONO9
LIGHT_SECONDARY=$LIGHT_MONO10
LIGHT_TERTIARY=$LIGHT_MONO11
LIGHT_FG=$LIGHT_MONO12
LIGHT_EMPHASIS=$LIGHT_MONO13
LIGHT_STRONG=$LIGHT_MONO14
LIGHT_BRIGHT=$LIGHT_MONO15
LIGHT_INTENSE=$LIGHT_MONO16

# --- Semantic accent aliases (dark) ---
DARK_ERROR=$DARK_RED
DARK_WARNING=$DARK_YELLOW
DARK_OK=$DARK_GREEN
DARK_INFO=$DARK_AQUA
DARK_HINT=$DARK_BLUE
DARK_SEARCH=$DARK_ORANGE
DARK_VCS_ADD=$DARK_GREEN
DARK_VCS_CHANGE=$DARK_BLUE
DARK_VCS_REMOVE=$DARK_RED

# --- Semantic accent aliases (light) ---
LIGHT_ERROR=$LIGHT_RED
LIGHT_WARNING=$LIGHT_YELLOW
LIGHT_OK=$LIGHT_GREEN
LIGHT_INFO=$LIGHT_AQUA
LIGHT_HINT=$LIGHT_BLUE
LIGHT_SEARCH=$LIGHT_ORANGE
LIGHT_VCS_ADD=$LIGHT_GREEN
LIGHT_VCS_CHANGE=$LIGHT_BLUE
LIGHT_VCS_REMOVE=$LIGHT_RED

# --- Semantic diff background aliases ---
DARK_DIFF_ADD=$DARK_BG_GREEN
DARK_DIFF_CHANGE=$DARK_BG_BLUE
DARK_DIFF_REMOVE=$DARK_BG_RED
LIGHT_DIFF_ADD=$LIGHT_BG_GREEN
LIGHT_DIFF_CHANGE=$LIGHT_BG_BLUE
LIGHT_DIFF_REMOVE=$LIGHT_BG_RED
