splash = false

wallpaper {
    monitor = DP-3
    path = ~/.config/backgrounds/warhammer_wallpeaper_man.jpg
    fit_mode = cover
}

wallpaper {
    monitor = HDMI-A-1
    path = ~/.config/backgrounds/warhammer_wallpeaper_imperium.jpg
    fit_mode = contain
}
